site_name: Python Pr치ctico
theme:
  name: readthedocs
  hljs_languages:
    - python
    - shell
    - bash
nav:
  - Sobre el curso: README.md
  - Temario: temario.md
  - Preguntas: faq.md
  - 0 Empiece aqui: 0.md
  - 1 Intro a Python: 1.md
  - 2 Trabajando con Data: 2.md
  - 3 Organizaci칩n de un Programa: 3.md
  - 4 Clases y Objetos: 4.md
  - 5 Entra침as del Objeto: 5.md
  - 6 Generadores: 6.md
  - 7 Temas avanzados: 7.md
  - 8 Prueba y Depuraci칩n: 8.md
  - 9 Paquetes: 9.md
  - Licencia: licencia.md
